# Generated by Django 4.0 on 2022-03-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
