# Generated by Django 4.0 on 2022-03-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='groups.group'),
        ),
    ]
