# Generated by Django 4.0 on 2022-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
